SET MODE MySQL;

CREATE TABLE IF NOT EXISTS categories (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(250) NOT NULL,
    parentId INT NOT NULL,
    UNIQUE(name),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(36) NOT NULL,
    name VARCHAR(250),
    price DECIMAL(10,2) NOT NULL,
    categoryPath VARCHAR(250) NOT NULL,
    PRIMARY KEY(id)
);